import { LucideIcon } from 'lucide-react';

export interface ReportColumn {
    key: string;
    label: string;
    type: 'text' | 'number' | 'currency' | 'date' | 'badge';
    align?: 'left' | 'right' | 'center';
    format?: (value: any) => string;
}

export interface ReportDefinition {
    id: string;
    title: string;
    description: string;
    category: ReportCategory;
    columns: ReportColumn[];
    dataSource: string; // Key for store/data access
    showTotals?: boolean;
    drillDown?: boolean;
    icon?: LucideIcon;
}

export type ReportCategory =
    | 'SALES'
    | 'EXPENSE'
    | 'CREDIT'
    | 'INVENTORY'
    | 'FINANCIAL'
    | 'SHIFT'
    | 'PROFIT_LOSS'
    | 'VARIANCE'
    | 'DISCOUNT'
    | 'AUDIT'
    | 'STAFF';

export const REPORT_REGISTRY: ReportDefinition[] = [
    // 1. SALES & REVENUE
    {
        id: 'sales-detailed',
        title: 'Detailed Sales Transaction Table',
        description: 'Complete list of nozzle-wise sales records across all shifts',
        category: 'SALES',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'shiftNumber', label: 'Shift', type: 'number' },
            { key: 'nozzleName', label: 'Nozzle', type: 'text' },
            { key: 'fuelType', label: 'Fuel Type', type: 'badge' },
            { key: 'liters', label: 'Liters', type: 'number', align: 'right' },
            { key: 'rate', label: 'Rate', type: 'currency', align: 'right' },
            { key: 'revenue', label: 'Amount', type: 'currency', align: 'right' },
            { key: 'staffName', label: 'Staff', type: 'text' },
        ],
        dataSource: 'shiftSales',
        showTotals: true,
        drillDown: true,
    },
    {
        id: 'fuel-hourly-pattern',
        title: 'Hourly Sales Pattern Report',
        description: 'Analysis of sales volume and revenue by hour to identify peak hours',
        category: 'SALES',
        columns: [
            { key: 'hour', label: 'Hour', type: 'text' },
            { key: 'pmsLiters', label: 'Petrol (L)', type: 'number', align: 'right' },
            { key: 'agoLiters', label: 'Diesel (L)', type: 'number', align: 'right' },
            { key: 'totalRevenue', label: 'Revenue', type: 'currency', align: 'right' },
            { key: 'transactions', label: 'Tx Count', type: 'number', align: 'center' },
        ],
        dataSource: 'hourlySales',
        showTotals: true,
    },
    {
        id: 'fuel-type-performance',
        title: 'Fuel Type Performance Report',
        description: 'Comparison of performance across different fuel types',
        category: 'SALES',
        columns: [
            { key: 'fuelType', label: 'Fuel Type', type: 'badge' },
            { key: 'volume', label: 'Quantity (L)', type: 'number', align: 'right' },
            { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
            { key: 'margin', label: 'Est. Margin', type: 'currency', align: 'right' },
            { key: 'share', label: 'Volume Share %', type: 'text', align: 'right' },
        ],
        dataSource: 'fuelPerformance',
    },
    {
        id: 'nozzle-efficiency',
        title: 'Pump/Nozzle Efficiency Report',
        description: 'Performance and downtime tracking per dispensing point',
        category: 'SALES',
        columns: [
            { key: 'nozzleName', label: 'Dispenser/Nozzle', type: 'text' },
            { key: 'totalLiters', label: 'Total Volume', type: 'number', align: 'right' },
            { key: 'totalTx', label: 'Tx Count', type: 'number', align: 'center' },
            { key: 'avgFlow', label: 'Avg Flow (L/min)', type: 'number', align: 'right' },
            { key: 'status', label: 'Health Status', type: 'badge' },
        ],
        dataSource: 'nozzleStats',
    },
    // 2. EXPENSE REPORTS
    {
        id: 'expense-detailed',
        title: 'Detailed Expense Report',
        description: 'Accounting-grade list of all station expenditures',
        category: 'EXPENSE',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'category', label: 'Category', type: 'badge' },
            { key: 'description', label: 'Description', type: 'text' },
            { key: 'shiftId', label: 'Shift', type: 'text' },
            { key: 'staffName', label: 'Staff', type: 'text' },
            { key: 'vendor', label: 'Vendor/Paid To', type: 'text' },
            { key: 'paymentMode', label: 'Payment Mode', type: 'badge' },
            { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
        ],
        dataSource: 'expenses',
        showTotals: true,
    },
    // 3. CREDIT & CUSTOMER LEDGER
    {
        id: 'customer-ledger',
        title: 'Credit Customer Ledger',
        description: 'Mandatory ledger tracking customer balances and fuel intake',
        category: 'CREDIT',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'customerName', label: 'Customer', type: 'text' },
            { key: 'type', label: 'Description', type: 'badge' },
            { key: 'openingBalance', label: 'Opening', type: 'currency', align: 'right' },
            { key: 'debit', label: 'Fuel Taken', type: 'currency', align: 'right' },
            { key: 'credit', label: 'Payment', type: 'currency', align: 'right' },
            { key: 'balance', label: 'Closing Balance', type: 'currency', align: 'right' },
        ],
        dataSource: 'customerLedger',
        showTotals: false,
    },
    {
        id: 'outstanding-non-recovery',
        title: 'Outstanding & Risk Analysis',
        description: 'Analysis of customers with non-recovery in 30/60/90 days',
        category: 'CREDIT',
        columns: [
            { key: 'customerName', label: 'Customer', type: 'text' },
            { key: 'balance', label: 'Outstanding Amount', type: 'currency', align: 'right' },
            { key: 'lastPaymentDate', label: 'Last Payment', type: 'date' },
            { key: 'daysSinceLast', label: 'Days Since Recovery', type: 'number', align: 'center' },
            { key: 'riskLevel', label: 'Risk Level', type: 'badge' },
        ],
        dataSource: 'customerAging',
    },
    // 4. INVENTORY & STOCK
    {
        id: 'inventory-movement',
        title: 'Inventory & Stock Movement',
        description: 'Precise tracking of fuel levels per tank with variance auditing',
        category: 'INVENTORY',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'tankName', label: 'Tank', type: 'text' },
            { key: 'openingStock', label: 'Opening Stock', type: 'number', align: 'right' },
            { key: 'received', label: 'Received', type: 'number', align: 'right' },
            { key: 'sold', label: 'Sold', type: 'number', align: 'right' },
            { key: 'closingStock', label: 'Closing Stock', type: 'number', align: 'right' },
            { key: 'variance', label: 'Variance', type: 'number', align: 'right' },
        ],
        dataSource: 'inventoryHistory',
        showTotals: true,
    },
    {
        id: 'tank-status-active',
        title: 'Live Tank Status Report',
        description: 'Real-time volume and available capacity across all storage tanks',
        category: 'INVENTORY',
        columns: [
            { key: 'tankName', label: 'Tank', type: 'text' },
            { key: 'fuelType', label: 'Fuel Type', type: 'badge' },
            { key: 'currentLevel', label: 'Current (L)', type: 'number', align: 'right' },
            { key: 'capacity', label: 'Capacity (L)', type: 'number', align: 'right' },
            { key: 'percentage', label: 'Fill %', type: 'text', align: 'center' },
            { key: 'reorder', label: 'Reorder Link', type: 'badge' },
        ],
        dataSource: 'tankStatus',
    },
    {
        id: 'fuel-receipts',
        title: 'Fuel Receipt & Delivery Report',
        description: 'Log of all fuel tanker arrivals and unloading records',
        category: 'INVENTORY',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'tankerId', label: 'Tanker #', type: 'text' },
            { key: 'supplier', label: 'Supplier', type: 'text' },
            { key: 'fuelType', label: 'Fuel Type', type: 'badge' },
            { key: 'qtyExpected', label: 'Ordered', type: 'number', align: 'right' },
            { key: 'qtyReceived', label: 'Actual', type: 'number', align: 'right' },
            { key: 'shortage', label: 'Shortage', type: 'number', align: 'right' },
        ],
        dataSource: 'fuelReceipts',
        showTotals: true,
    },
    {
        id: 'evaporation-loss',
        title: 'Fuel Evaporation & Spillage Report',
        description: 'Analysis of environmental and handling losses over time',
        category: 'INVENTORY',
        columns: [
            { key: 'month', label: 'Month', type: 'text' },
            { key: 'fuelType', label: 'Fuel Type', type: 'badge' },
            { key: 'totalVolume', label: 'Throughput', type: 'number', align: 'right' },
            { key: 'estLoss', label: 'Est Loss (L)', type: 'number', align: 'right' },
            { key: 'lossPercent', label: 'Loss %', type: 'text', align: 'right' },
        ],
        dataSource: 'evaporationStats',
    },
    {
        id: 'meter-calibration',
        title: 'Meter Calculation & Accuracy Report',
        description: 'Nozzle calibration logs and meter verification audits',
        category: 'VARIANCE',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'nozzleName', label: 'Nozzle', type: 'text' },
            { key: 'meterReading', label: 'Meter Reading', type: 'number', align: 'right' },
            { key: 'physicalReading', label: 'Manual Dip/Recal', type: 'number', align: 'right' },
            { key: 'diff', label: 'Difference', type: 'number', align: 'right' },
            { key: 'status', label: 'Status', type: 'badge' },
        ],
        dataSource: 'meterAudits',
    },
    // 6. SHIFT & OPERATOR
    {
        id: 'staff-performance',
        title: 'Staff Performance & Efficiency',
        description: 'Analysis of staff sales, error rates, and shift attendance',
        category: 'SHIFT',
        columns: [
            { key: 'staffName', label: 'Staff Member', type: 'text' },
            { key: 'totalShifts', label: 'Shifts worked', type: 'number', align: 'center' },
            { key: 'totalSales', label: 'Sales Amount', type: 'currency', align: 'right' },
            { key: 'avgVariance', label: 'Avg Variance', type: 'currency', align: 'right' },
            { key: 'efficiency', label: 'Efficiency Score', type: 'badge' },
        ],
        dataSource: 'staffPerformance',
    },
    // 8. LOSS & VARIANCE
    {
        id: 'variance-investigation',
        title: 'Loss & Variance Investigation',
        description: 'Detailed analysis of unexplained shortages or leakages',
        category: 'VARIANCE',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'area', label: 'Area / Point', type: 'text' },
            { key: 'expected', label: 'Expected Value', type: 'currency', align: 'right' },
            { key: 'actual', label: 'Actual Value', type: 'currency', align: 'right' },
            { key: 'variance', label: 'Variance', type: 'currency', align: 'right' },
            { key: 'explanation', label: 'Staff Explanation', type: 'text' },
        ],
        dataSource: 'variances',
        showTotals: true,
    },
    // 9. RATE IMPACT
    {
        id: 'rate-impact-analysis',
        title: 'Rate Change Impact Table',
        description: 'History of price changes and their impact on sales volume',
        category: 'DISCOUNT',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'oldRate', label: 'Old Rate', type: 'currency', align: 'right' },
            { key: 'newRate', label: 'New Rate', type: 'currency', align: 'right' },
            { key: 'volBefore', label: 'Vol Before', type: 'number', align: 'right' },
            { key: 'volAfter', label: 'Vol After', type: 'number', align: 'right' },
            { key: 'impact', label: 'Impact / Revenue Change', type: 'currency', align: 'right' },
        ],
        dataSource: 'rateImpacts',
    },
    {
        id: 'profit-ledger',
        title: 'Profit & Margin Ledger',
        description:
            'Deep-dive into margins, carriage costs, and net profitability per transaction',
        category: 'PROFIT_LOSS',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'type', label: 'Type', type: 'badge' },
            { key: 'description', label: 'Description', type: 'text' },
            { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
            { key: 'cost', label: 'Cost', type: 'currency', align: 'right' },
            { key: 'carriage', label: 'Carriage', type: 'currency', align: 'right' },
            { key: 'netProfit', label: 'Net Profit', type: 'currency', align: 'right' },
        ],
        dataSource: 'profitLedger',
        showTotals: true,
    },
    // 13. CASH & BANK LEDGER
    {
        id: 'cash-bank-ledger',
        title: 'Cash & Bank Ledger Table',
        description: 'Chronological tracking of cash movement across accounts',
        category: 'FINANCIAL',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'accountName', label: 'Account', type: 'text' },
            { key: 'opening', label: 'Opening', type: 'currency', align: 'right' },
            { key: 'credit', label: 'Inflow', type: 'currency', align: 'right' },
            { key: 'debit', label: 'Outflow', type: 'currency', align: 'right' },
            { key: 'balance', label: 'Closing', type: 'currency', align: 'right' },
        ],
        dataSource: 'cashLedger',
    },
    {
        id: 'individual-customer-report',
        title: 'Individual Customer Performance',
        description: 'Monthly & yearly fuel take analysis per customer',
        category: 'CREDIT',
        columns: [
            { key: 'month', label: 'Month', type: 'text' },
            { key: 'fuelTaken', label: 'Fuel Taken', type: 'currency', align: 'right' },
            { key: 'payments', label: 'Payments Made', type: 'currency', align: 'right' },
            { key: 'discounts', label: 'Discounts', type: 'currency', align: 'right' },
            { key: 'balance', label: 'Closing Balance', type: 'currency', align: 'right' },
        ],
        dataSource: 'customerPerformance',
    },
    {
        id: 'supplier-ledger-detailed',
        title: 'Supplier Payment Ledger',
        description: 'Comprehensive tracking of invoices, bank payments, and balances',
        category: 'FINANCIAL',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'supplierName', label: 'Supplier', type: 'text' },
            { key: 'invoiceNo', label: 'Invoice No', type: 'text' },
            { key: 'amount', label: 'Invoice Amount', type: 'currency', align: 'right' },
            { key: 'paid', label: 'Amount Paid', type: 'currency', align: 'right' },
            { key: 'balance', label: 'Payable Balance', type: 'currency', align: 'right' },
        ],
        dataSource: 'supplierLedger',
    },
    // 16. MASTER REPORTS
    {
        id: 'today-pulse',
        title: "Today's Business Pulse",
        description: 'Comprehensive chronological list of every activity performed today',
        category: 'AUDIT',
        columns: [
            { key: 'timestamp', label: 'Time', type: 'text' }, // We'll format this specially
            { key: 'type', label: 'Entry Type', type: 'badge' },
            { key: 'description', label: 'Action Details', type: 'text' },
            { key: 'amount', label: 'Value (₨)', type: 'currency', align: 'right' },
            { key: 'staff', label: 'User/Staff', type: 'text' },
        ],
        dataSource: 'masterPulse',
        showTotals: true,
    },
    {
        id: 'shift-reconciliation-all',
        title: 'Shift A-to-Z Reconciliation',
        description: 'Reading-to-Cash audit for every shift ever recorded',
        category: 'SHIFT',
        columns: [
            { key: 'shiftNumber', label: 'Shift #', type: 'number' },
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'staffName', label: 'Staff Member', type: 'text' },
            { key: 'totalSales', label: 'Total Revenue', type: 'currency', align: 'right' },
            { key: 'totalCash', label: 'Physical Cash', type: 'currency', align: 'right' },
            { key: 'variance', label: 'Variance', type: 'currency', align: 'right' },
            { key: 'status', label: 'Audit Status', type: 'badge' },
        ],
        dataSource: 'shiftArchive',
        drillDown: true,
    },
    {
        id: 'staff-ledger-detailed',
        title: 'Staff Ledger Detailed',
        description: 'Complete transaction history for a specific staff member',
        category: 'AUDIT',
        columns: [
            { key: 'date', label: 'Date', type: 'text' },
            { key: 'type', label: 'Type', type: 'badge' },
            { key: 'reference', label: 'Ref #', type: 'text' },
            { key: 'note', label: 'Description', type: 'text' },
            { key: 'debit', label: 'Payments (₨)', type: 'currency', align: 'right' },
            { key: 'credit', label: 'Earnings (₨)', type: 'currency', align: 'right' },
            { key: 'balance', label: 'Balance (₨)', type: 'currency', align: 'right' },
        ],
        dataSource: 'staffLedger',
        showTotals: true,
    },

    // 17. LUBE SPECIFIC REPORTS
    {
        id: 'lube-sales-detailed',
        title: 'Lube Advanced Sales Report',
        description: 'Detailed traceability of Lube retail sales with batch and margin tracking',
        category: 'SALES',
        columns: [
            { key: 'timestamp', label: 'Date/Time', type: 'date' },
            { key: 'receiptNumber', label: 'Receipt', type: 'text' },
            { key: 'customerName', label: 'Customer', type: 'text' },
            { key: 'itemsCount', label: 'Items', type: 'number', align: 'center' },
            { key: 'subtotal', label: 'Subtotal', type: 'currency', align: 'right' },
            { key: 'discount', label: 'Discount', type: 'currency', align: 'right' },
            { key: 'totalAmount', label: 'Total', type: 'currency', align: 'right' },
            { key: 'paymentMethod', label: 'Payment', type: 'badge' },
        ],
        dataSource: 'lubeSales',
        showTotals: true,
        drillDown: true,
    },
    {
        id: 'lube-inventory-movement',
        title: 'Lube Inventory Tracking',
        description: 'SKU-level movement tracking including stock-ins, sales, and adjustments',
        category: 'INVENTORY',
        columns: [
            { key: 'productName', label: 'Product', type: 'text' },
            { key: 'category', label: 'Category', type: 'badge' },
            { key: 'openingStock', label: 'Opening', type: 'number', align: 'right' },
            { key: 'received', label: 'Inbound', type: 'number', align: 'right' },
            { key: 'sold', label: 'Outbound', type: 'number', align: 'right' },
            { key: 'adjustments', label: 'Adj', type: 'number', align: 'right' },
            { key: 'closingStock', label: 'Closing', type: 'number', align: 'right' },
        ],
        dataSource: 'lubeInventory',
        showTotals: true,
    },
    {
        id: 'lube-profit-summary',
        title: 'Lube Profitability Analysis',
        description:
            'Detailed breakdown of realized profit from Lube sales after carriage and costs',
        category: 'PROFIT_LOSS',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'revenue', label: 'Total Revenue', type: 'currency', align: 'right' },
            { key: 'cost', label: 'Total Cost', type: 'currency', align: 'right' },
            { key: 'grossProfit', label: 'Gross Profit', type: 'currency', align: 'right' },
            { key: 'expenses', label: 'Mapped Expenses', type: 'currency', align: 'right' },
            { key: 'netProfit', label: 'Net Lube Profit', type: 'currency', align: 'right' },
        ],
        dataSource: 'lubeProfit',
        showTotals: true,
    },
    {
        id: 'lube-discounts',
        title: 'Discount & Promotion Audit',
        description: 'Traceability for every discount given in Lube POS (Fixed vs Percentage)',
        category: 'DISCOUNT',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'receiptNumber', label: 'Receipt', type: 'text' },
            { key: 'subtotal', label: 'Original', type: 'currency', align: 'right' },
            { key: 'discountAmount', label: 'Discount', type: 'currency', align: 'right' },
            { key: 'netAmount', label: 'Final Sale', type: 'currency', align: 'right' },
            { key: 'staffName', label: 'Cashier', type: 'text' },
        ],
        dataSource: 'lubeDiscounts',
        showTotals: true,
    },
    {
        id: 'lube-expenses',
        title: 'Lube Operational Expenses',
        description: 'Detailed list of expenses specifically tagged under Lube operations',
        category: 'EXPENSE',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'accountName', label: 'Source', type: 'text' },
            { key: 'description', label: 'Reason', type: 'text' },
            { key: 'vendor', label: 'Paid To', type: 'text' },
            { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
        ],
        dataSource: 'lubeExpenses',
        showTotals: true,
    },
    {
        id: 'lube-recoveries',
        title: 'Lube Credit Recoveries',
        description: 'Tracking recovery of credit payments for Lube transactions',
        category: 'CREDIT',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'customerName', label: 'Customer', type: 'text' },
            { key: 'amount', label: 'Recovery Amount', type: 'currency', align: 'right' },
            { key: 'paymentMode', label: 'Mode', type: 'badge' },
            { key: 'staffName', label: 'Collected By', type: 'text' },
        ],
        dataSource: 'lubeRecoveries',
        showTotals: true,
    },
    {
        id: 'lube-bank-cash',
        title: 'Lube Bank & Cash Reconciliation',
        description: 'Daily reconciliation of cash in hand vs bank deposits for Lube desk',
        category: 'FINANCIAL',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'opening', label: 'Opening', type: 'currency', align: 'right' },
            { key: 'cashSales', label: 'Cash Sales', type: 'currency', align: 'right' },
            { key: 'bankDeposits', label: 'Bank Deposits', type: 'currency', align: 'right' },
            { key: 'expenses', label: 'Cash Expenses', type: 'currency', align: 'right' },
            { key: 'closing', label: 'Closing', type: 'currency', align: 'right' },
        ],
        dataSource: 'lubeFinancials',
        showTotals: true,
    },
    {
        id: 'lube-digital-cash',
        title: 'Digital Payment Audit',
        description: 'Tracking card and mobile wallet transactions for Lube products',
        category: 'FINANCIAL',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'receiptNumber', label: 'Receipt', type: 'text' },
            { key: 'method', label: 'Digital Mode', type: 'badge' },
            { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
            { key: 'status', label: 'Status', type: 'badge' },
        ],
        dataSource: 'lubeDigital',
        showTotals: true,
    },
    {
        id: 'lube-brand-performance',
        title: 'Lube Brand Performance Report',
        description: 'Sales and profitability analysis by lubricant brand',
        category: 'SALES',
        columns: [
            { key: 'brand', label: 'Brand', type: 'text' },
            { key: 'volume', label: 'Volume (L/Units)', type: 'number', align: 'right' },
            { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
            { key: 'profit', label: 'Gross Profit', type: 'currency', align: 'right' },
            { key: 'growth', label: 'Growth %', type: 'badge' },
        ],
        dataSource: 'lubeBrandPerf',
    },
    {
        id: 'lube-viscosity-analysis',
        title: 'Viscosity Grade Sales Analysis',
        description: 'Sales breakdown by oil grade (5W-30, 20W-50, etc.)',
        category: 'SALES',
        columns: [
            { key: 'viscosity', label: 'Viscosity Grade', type: 'badge' },
            { key: 'volume', label: 'Volume Sold', type: 'number', align: 'right' },
            { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
            { key: 'popPercent', label: 'Popularity %', type: 'text', align: 'right' },
        ],
        dataSource: 'lubeViscosity',
    },
    {
        id: 'lube-sku-velocity',
        title: 'SKU Sales Velocity & ABC Analysis',
        description: 'Fast-moving vs slow-moving lube products',
        category: 'INVENTORY',
        columns: [
            { key: 'productName', label: 'Product/SKU', type: 'text' },
            { key: 'salesCount', label: '30-Day Sales', type: 'number', align: 'right' },
            { key: 'velocity', label: 'Velocity', type: 'badge' },
            { key: 'abcClass', label: 'ABC Class', type: 'badge' },
            { key: 'turns', label: 'Stock Turns', type: 'number', align: 'right' },
        ],
        dataSource: 'lubeSKUVelocity',
    },
    {
        id: 'lube-service-conversion',
        title: 'Service Bay Conversion Report',
        description: 'Percentage of oil change customers purchasing lube products',
        category: 'SALES',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'serviceCount', label: 'Total Services', type: 'number', align: 'center' },
            { key: 'lubeSoldCount', label: 'Lube Sales', type: 'number', align: 'center' },
            { key: 'conversionRate', label: 'Conversion %', type: 'text', align: 'right' },
            { key: 'avgTicket', label: 'Avg Ticket', type: 'currency', align: 'right' },
        ],
        dataSource: 'lubeServiceConversion',
    },
    {
        id: 'lube-stock-receipts',
        title: 'Lube Purchase & Stock Receipt History',
        description: 'Log of all lube inventory receiving and landed costs',
        category: 'INVENTORY',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'supplier', label: 'Supplier', type: 'text' },
            { key: 'poNumber', label: 'PO #', type: 'text' },
            { key: 'itemsReceived', label: 'Items', type: 'number', align: 'center' },
            { key: 'totalLandedCost', label: 'Landed Cost', type: 'currency', align: 'right' },
            { key: 'status', label: 'Status', type: 'badge' },
        ],
        dataSource: 'lubeReceiptHistory',
    },

    // 18. CNG SPECIFIC REPORTS
    {
        id: 'cng-sales-detailed',
        title: 'CNG Detailed Sales Report',
        description: 'Sold KGs, Test KGs, and Revenue analysis per shift',
        category: 'SALES',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'shiftNumber', label: 'Shift', type: 'number' },
            { key: 'staffName', label: 'Staff', type: 'text' },
            { key: 'soldKgs', label: 'Sold KGs', type: 'number', align: 'right' },
            { key: 'testKgs', label: 'Test KGs', type: 'number', align: 'right' },
            { key: 'rate', label: 'Rate/KG', type: 'currency', align: 'right' },
            { key: 'revenue', label: 'Total Revenue', type: 'currency', align: 'right' },
        ],
        dataSource: 'cngSales',
        showTotals: true,
    },
    {
        id: 'cng-inventory-history',
        title: 'CNG Inventory & Cascade Audit',
        description: 'Tracking received KGs and inventory levels in cascade banks',
        category: 'INVENTORY',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'reference', label: 'Ref #', type: 'text' },
            { key: 'received', label: 'KGs Received', type: 'number', align: 'right' },
            { key: 'pressureBefore', label: 'P-Before', type: 'number', align: 'right' },
            { key: 'pressureAfter', label: 'P-After', type: 'number', align: 'right' },
            { key: 'currentStock', label: 'Current KGs', type: 'number', align: 'right' },
        ],
        dataSource: 'cngInventory',
        showTotals: true,
    },
    {
        id: 'cng-discounts-detailed',
        title: 'CNG Discount Tracker',
        description: 'Audit of every discount granted during CNG shifts',
        category: 'DISCOUNT',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'customerName', label: 'Customer', type: 'text' },
            { key: 'amount', label: 'Discount (₨)', type: 'currency', align: 'right' },
            { key: 'reason', label: 'Reason', type: 'badge' },
            { key: 'staffName', label: 'Provided By', type: 'text' },
        ],
        dataSource: 'cngDiscounts',
        showTotals: true,
    },
    {
        id: 'cng-vehicle-analysis',
        title: 'CNG Vehicle Type Analysis',
        description: 'Breakdown of sales by vehicle category (Private, Commercial, Public)',
        category: 'SALES',
        columns: [
            { key: 'vehicleType', label: 'Vehicle Type', type: 'badge' },
            { key: 'count', label: 'Visit Count', type: 'number', align: 'center' },
            { key: 'volume', label: 'Total KGs', type: 'number', align: 'right' },
            { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
            { key: 'avgKg', label: 'Avg KG/Visit', type: 'number', align: 'right' },
        ],
        dataSource: 'cngVehicleType',
    },
    {
        id: 'cng-pressure-impact',
        title: 'Cascade Pressure Impact Report',
        description: 'Correlation between fill pressure and dispensing efficiency',
        category: 'VARIANCE',
        columns: [
            { key: 'pressureRange', label: 'Pressure (PSI)', type: 'text' },
            { key: 'fillCount', label: 'Fills', type: 'number', align: 'center' },
            { key: 'avgFillTime', label: 'Avg Time (min)', type: 'number', align: 'right' },
            { key: 'totalKg', label: 'Total KGs', type: 'number', align: 'right' },
            { key: 'efficiency', label: 'Efficiency %', type: 'text', align: 'right' },
        ],
        dataSource: 'cngPressureStats',
    },
    {
        id: 'cng-compression-efficiency',
        title: 'Compression & Energy Efficiency',
        description: 'Energy consumption vs CNG compressed and dispensed',
        category: 'FINANCIAL',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'unitsConsumed', label: 'KWh Units', type: 'number', align: 'right' },
            { key: 'kgsCompressed', label: 'KGs Compressed', type: 'number', align: 'right' },
            { key: 'costPerKg', label: 'Power Cost/KG', type: 'currency', align: 'right' },
            { key: 'uptime', label: 'Status', type: 'badge' },
        ],
        dataSource: 'cngEnergy',
    },
    {
        id: 'cng-source-receipts',
        title: 'Source Gas Receipt Log',
        description: 'Detailed log of gas received from main supply lines',
        category: 'INVENTORY',
        columns: [
            { key: 'timestamp', label: 'Received Time', type: 'date' },
            { key: 'meterStart', label: 'Meter Start', type: 'number', align: 'right' },
            { key: 'meterEnd', label: 'Meter End', type: 'number', align: 'right' },
            { key: 'volumeMMSCF', label: 'Volume (MMSCF)', type: 'number', align: 'right' },
            { key: 'equivalentKg', label: 'Equiv. KGs', type: 'number', align: 'right' },
        ],
        dataSource: 'cngReceipts',
    },
    {
        id: 'fin-profit-loss',
        title: 'Business Profit & Loss Summary',
        description: 'Monthly P&L overview across all business units',
        category: 'FINANCIAL',
        columns: [
            { key: 'period', label: 'Period', type: 'text' },
            { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
            { key: 'cogs', label: 'COGS', type: 'currency', align: 'right' },
            { key: 'expenses', label: 'Expenses', type: 'currency', align: 'right' },
            { key: 'netProfit', label: 'Net Profit', type: 'currency', align: 'right' },
        ],
        dataSource: 'finPL',
    },
    {
        id: 'hr-attendance-summary',
        title: 'Staff Attendance & Late Log',
        description: 'Monthly summary of attendance, late arrivals, and leaves',
        category: 'STAFF',
        columns: [
            { key: 'staffName', label: 'Staff Member', type: 'text' },
            { key: 'presentDays', label: 'Present', type: 'number', align: 'center' },
            { key: 'lateDays', label: 'Late', type: 'number', align: 'center' },
            { key: 'leaves', label: 'Leaves', type: 'number', align: 'center' },
            { key: 'netSalary', label: 'Earned Salary', type: 'currency', align: 'right' },
        ],
        dataSource: 'hrAttendance',
    },
    {
        id: 'audit-price-changes',
        title: 'Price Change Audit Log',
        description: 'History of every fuel and lube price modification',
        category: 'AUDIT',
        columns: [
            { key: 'timestamp', label: 'Time', type: 'date' },
            { key: 'item', label: 'Item/Fuel', type: 'text' },
            { key: 'oldPrice', label: 'Old Price', type: 'currency', align: 'right' },
            { key: 'newPrice', label: 'New Price', type: 'currency', align: 'right' },
            { key: 'changedBy', label: 'Changed By', type: 'text' },
        ],
        dataSource: 'auditPrices',
    },
    {
        id: 'comp-safety-audit',
        title: 'Safety & Environmental Incident Log',
        description: 'Record of spillage, safety drills, and compliance checks',
        category: 'AUDIT',
        columns: [
            { key: 'date', label: 'Date', type: 'date' },
            { key: 'incidentType', label: 'Incident/Check', type: 'badge' },
            { key: 'description', label: 'Description', type: 'text' },
            { key: 'status', label: 'Status', type: 'badge' },
            { key: 'reportedBy', label: 'Reported By', type: 'text' },
        ],
        dataSource: 'compSafety',
    },
    {
        id: 'audit-system-access',
        title: 'System Access & Security Log',
        description: 'Audit of user logins, logout with IP and device tracking',
        category: 'AUDIT',
        columns: [
            { key: 'timestamp', label: 'Time', type: 'date' },
            { key: 'userName', label: 'Staff Member', type: 'text' },
            { key: 'action', label: 'Action', type: 'badge' },
            { key: 'ipAddress', label: 'IP Address', type: 'text' },
            { key: 'status', label: 'Result', type: 'badge' },
        ],
        dataSource: 'auditAccess',
    },
];

export const REPORT_CATEGORIES = [
    { id: 'SALES', name: 'Sales & Revenue', color: 'blue' },
    { id: 'EXPENSE', name: 'Deep Expense Reports', color: 'rose' },
    { id: 'CREDIT', name: 'Credit & Customer Ledger', color: 'emerald' },
    { id: 'INVENTORY', name: 'Inventory & Stock History', color: 'amber' },
    { id: 'FINANCIAL', name: 'Cash, Bank & Payments', color: 'indigo' },
    { id: 'PROFIT_LOSS', name: 'Profit & Loss Analysis', color: 'teal' },
    { id: 'SHIFT', name: 'Shift & Operator Data', color: 'purple' },
    { id: 'VARIANCE', name: 'Loss & Leakage Audit', color: 'orange' },
    { id: 'DISCOUNT', name: 'Discount Analysis', color: 'pink' },
    { id: 'AUDIT', name: 'System Audit & Control', color: 'slate' },
];
